### ISSUE TITLE
[동적 Div 기술 증명- TEXT] From 10/26 - 10/28 due: Front-End 김남현, 박덕원

### ISSUE THREAD

**Issue by nick0726** [codestates/Withyou#7]
## ISSUE
- Group: client
- Type: Skill Research
- Detail: Vanlia JS 기술 알아보기 

## TODO: 동적 div 선택 및 드래그, 기능 작동 확인! From 10/26 - 10/28 due
- [ ] Job1: 동적 div를 만들 수 있는 Vanlia JS 기술 알아보기 

- [ ] Job2: 세부 기능 확인- TEXT
  - [ ] 버튼을 눌렀을 때, 어떤 영역 내에 element가 동적으로 생성된다.
  - [ ] 해당 element는 선택 가능하다.
  - [ ] 선택한 element는 삭제 가능하다.
  - [ ] 선택한 element는 위치 조절이 가능하다.
 
##Estimated time
**Pick one**
- [ ] 0.5h
- [ ] 1h
- [ ] 1.5h
- [ ] 2h
- [ ] 2.5h
- [ ] 3h

##Labels
- Estimated time: E: From min 2 days to max 4 days
- Group : client
- Sprint: Sprint__Dance Party: 객체지향 프로그래밍
- Urgency: High, Super High
